version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: sql-test-postgres
    environment:
      POSTGRES_DB: employee_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: sql-test-adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
